version: '3.5'
services:
    # 10.10.1.4
    web:
        build: .
        container_name: web
        hostname: web
        volumes:
            - ./web/MoviesLibrary:/var/www/MoviesLibrary
            - ./web/apache_django.conf:/etc/apache2/sites-available/000-default.conf
            - ./web/startup.sh:/var/www/startup.sh
        depends_on:
            - mysql-db
            - mongo_db
        ports: 
            - "8000:80"
        command: server
        networks:
            default:
                ipv4_address: 10.10.1.4
    # 10.10.1.5
    keyrock:
        image: fiware/idm:latest
        container_name: fiware-keyrock
        hostname: keyrock
        networks:
            default:
                ipv4_address: 10.10.1.5
        depends_on:
            - mysql-db
        ports:
            - '3000:3000'
            - '443:443'
        environment:
            - DEBUG=idm:*
            - IDM_DB_HOST=mysql-db
            - IDM_HOST=http://localhost:3000
            - IDM_PORT=3000
            # Development use only
            # Use Docker Secrets for Sensitive Data
            - IDM_DB_PASS=secret
            - IDM_DB_USER=root
            - IDM_ADMIN_USER=admin
            - IDM_ADMIN_EMAIL=admin@test.com
            - IDM_ADMIN_PASS=1234
    # 10.10.1.6
    mysql-db:
        restart: always
        image: mysql:5.7
        hostname: mysql-db
        container_name: db-mysql
        expose:
            - '3306'
        ports:
            - '3306:3306'
        networks:
            default:
                ipv4_address: 10.10.1.6
        environment:
            # Development use only
            # Use Docker Secrets for Sensitive Data
            - 'MYSQL_DATABASE=admin'
            - 'MYSQL_ROOT_PASSWORD=secret'
            - 'MYSQL_ROOT_HOST=%'
        volumes:
            - ./mysql_data:/docker-entrypoint-initdb.d
    # 10.10.1.7
    mongo_db:
        image: mongo
        restart: always
        container_name: mongo_db
        hostname: mongo_db
        ports: 
            - '27018:27017'
        volumes: 
            - mongo_db:/data/db
            - ./mongo_data/data:/home
            - ./mongo_data/docker-entrypoint.sh:/docker-entrypoint-initdb.d/docker-entrypoint.sh
        networks:
            default:
                ipv4_address: 10.10.1.7
    # 10.10.1.2
    data_storage:
        build: 
            context : ./data_storage_service
        command: python api.py
        restart: always
        container_name: data_storage_api
        volumes:
            - ./data_storage_service:/api
        ports:
            - '5000:5000'
        networks:
            default:
                ipv4_address: 10.10.1.2
        environment: 
            - PYTHONUNBUFFERED=1
    # 10.10.1.3
    pep_proxy_wilma:
        image: fiware/pep-proxy
        container_name: wilma
        depends_on: 
            - keyrock
        ports: 
            - '1027:1027'
        expose: 
            - '1027'
        environment: 
            - PEP_PROXY_APP_HOST=data_storage
            - PEP_PROXY_APP_PORT=5000
            - PEP_PROXY_PORT=1027
            - PEP_PROXY_IDM_HOST=keyrock
            - PEP_PROXY_HTTPS_ENABLED=false
            - PEP_PROXY_AUTH_ENABLED=false
            - PEP_PROXY_IDM_SSL_ENABLED=false
            - PEP_PROXY_IDM_PORT=3000
            - PEP_PROXY_APP_ID=47d89a60-79f3-423a-8898-1bfe823c3769
            - PEP_PROXY_USERNAME=pep_proxy_dae61432-4291-43b3-a183-cbd5418b2fb4
            - PEP_PASSWORD=pep_proxy_642cb410-2694-45a7-93f5-982b1c5547cd
            - PEP_PROXY_PDP=idm
            - PEP_PROXY_MAGIC_KEY=magic_key 
        networks: 
            default:
                ipv4_address: 10.10.1.3
    # 10.10.1.8
    orion:
        image: fiware/orion
        container_name: orion
        depends_on:
            - orion_mongo
        ports:
            - '1026:1026'
        command: -dbhost orion_mongo 
        networks:
            default:
                ipv4_address: 10.10.1.8
    # 10.10.1.9
    orion_mongo:
        image: mongo:3.2
        command: --nojournal
        container_name: orion_mongo
        hostname: orion_mongo
        ports: 
            - '27017:27017'
        volumes: 
            - orion_data:/data/db
        networks:
            default:
                ipv4_address: 10.10.1.9


networks:
    default:
        ipam:
            config:
                - subnet: 10.10.1.0/24

volumes:
    mysql-db: 
    mongo_db:
    orion_data:

