version: '3.5'
services:
    keyrock:
        image: fiware/idm:latest
        container_name: fiware-keyrock
        hostname: keyrock
        networks:
            default:
                ipv4_address: 10.10.1.5
        depends_on:
            - mysql-db
        ports:
            - '3000:3000'
            - '443:443'
        environment:
            - DEBUG=idm:*
            - IDM_DB_HOST=mysql-db
            - IDM_HOST=http://localhost:3000
            - IDM_PORT=3000
            # Development use only
            # Use Docker Secrets for Sensitive Data
            - IDM_DB_PASS=secret
            - IDM_DB_USER=root
            - IDM_ADMIN_USER=admin
            - IDM_ADMIN_EMAIL=admin@test.com
            - IDM_ADMIN_PASS=1234
            

    mysql-db:
        restart: always
        image: mysql:5.7
        hostname: mysql-db
        container_name: db-mysql
        expose:
            - '3306'
        ports:
            - '3306:3306'
        networks:
            default:
                ipv4_address: 10.10.1.6
        environment:
            # Development use only
            # Use Docker Secrets for Sensitive Data
            - 'MYSQL_ROOT_PASSWORD=secret'
            - 'MYSQL_ROOT_HOST=10.10.1.5'
        volumes:
            - ./mysql-db:/var/lib/mysql

    mongo_db:
        image: mongo
        restart: always
        container_name: mongo_db
        hostname: mongo_db
        ports: 
            - '27017:27017'
        volumes: 
            - ./mongo_db:/data/db
        networks:
            default:
                ipv4_address: 10.10.1.7

    data_storage:
        build: 
            context : ./data_storage_service
        command: python api.py
        restart: always
        container_name: data_storage_api
        volumes:
            - ./data_storage_service:/api
        ports:
            - '5000:5000'
        networks:
            default:
                ipv4_address: 10.10.1.2
    
    pep_proxy_wilma:
        image: fiware/pep-proxy
        container_name: wilma
        depends_on: 
            - keyrock
        ports: 
            - '1027:1027'
        expose: 
            - '1027'
        environment: 
            - PEP_PROXY_APP_HOST=data_storage
            - PEP_PROXY_APP_PORT=5000
            - PEP_PROXY_PORT=1027
            - PEP_PROXY_IDM_HOST=keyrock
            - PEP_PROXY_HTTPS_ENABLED=false
            - PEP_PROXY_AUTH_ENABLED=false
            - PEP_PROXY_IDM_SSL_ENABLED=false
            - PEP_PROXY_IDM_PORT=3000
            - PEP_PROXY_APP_ID=47d89a60-79f3-423a-8898-1bfe823c3769
            - PEP_PROXY_USERNAME=pep_proxy_dae61432-4291-43b3-a183-cbd5418b2fb4
            - PEP_PASSWORD=pep_proxy_642cb410-2694-45a7-93f5-982b1c5547cd
            - PEP_PROXY_PDP=idm
            - PEP_PROXY_MAGIC_KEY=magic_key 
        networks: 
            default:
                ipv4_address: 10.10.1.3

networks:
    default:
        ipam:
            config:
                - subnet: 10.10.1.0/24
volumes:
    mysql-db: 

